### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/tamara.golubovic#1]
Hi @TamaraG13, 

1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Close this ticket.
4. Go to https://github.com/orgs/alptium/teams/java-team/discussions and start doing the practical projects there (see discussions from bottom to top).

Thanks,
Valentina

**Comment by TamaraG13** [comment]
@valentinacupac primljeno :)

**Comment by valentinajemuovic** [comment]
Thanks @TamaraG13, please then do steps 3 & 4.
P.S. Also if you wish you can practice writing in English since most programming jobs require English.
