### ISSUE TITLE
Gradebook

### ISSUE THREAD

**Issue by TamaraG13** [alptium/tamara.golubovic#5]

**Comment by TamaraG13** [comment]
Task done @valentinacupac

**Comment by valentinajemuovic** [comment]
@TamaraG13, see https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comments 29 (indentation is not correct on your lines 30 & 31), comment 14, comment 19.

Also, all the data regarding student names and grades is directly in the code. However, I, as the teacher, want to be able to input the names and grades. Do you have any ideas how to do that?

**Comment by TamaraG13** [comment]
I have changed Gradebook, please check it @valentinacupac thank you!

**Comment by valentinajemuovic** [comment]
@TamaraG13, very good. After the inputted data, could you also do printing of summary of the students and their grades (i.e. you print out all the information that has been inputted, to show the listing of all students and their grades and THEN to put the sum of the grades.

This is just a small point, aside from that, good work!

**Comment by TamaraG13** [comment]
Yes, I will add that now. Thank you so much! :) here is the error 
![error](https://user-images.githubusercontent.com/36139219/36815869-62598220-1cdc-11e8-9d11-25677cf76743.JPG)

**Comment by valentinajemuovic** [comment]
@TamaraG13, see https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World comment 2.

**Comment by TamaraG13** [comment]
@valentinacupac the comment is regarding capital letters, but I have corrected that in Eclipse, long time ago but when I have commited the project first time iw was with capital lete but after that I couldn't change that with second commit. I am not sure how should I proceed.

**Comment by TamaraG13** [comment]
@valentinacupac I hope that I corrected everything now :)

**Comment by valentinajemuovic** [comment]
@TamaraG13, correct.
